Added a Playlist Class (broken)
Added a Playlist Class which is meant to collect the current Queue, when called from to_html in the HtmlAdapter class.
Getting a TypeError:
TypeError: HtmlAdapter.__init__() missing 1 required positional argument: 'song_list'